name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      args:
        description: 'args'
        required: false

env:
  GIT_AUTHOR_NAME: yseto
  GIT_AUTHOR_EMAIL: yseto@users.noreply.github.com
  GIT_COMMITTER_NAME: yseto
  GIT_COMMITTER_EMAIL: yseto@users.noreply.github.com

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: yseto/playground-action@test3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - run: echo $(date) >> date.txt && exit 1

